// <auto-generated />
namespace Class_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2017722 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2017722));
        
        string IMigrationMetadata.Id
        {
            get { return "201707020958405_2017-7-2-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
